### ISSUE TITLE
Reorganize pages.json info

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#144]
* Can we just include that info into document-metadata.json?
* maybe also look at the genetic bargraph data
* when we include sigil-based identifiers (https://github.com/faustedition/faust-web/issues/201) for everything, we can probably just use them plus the section number

**Comment by thvitt** [comment]
for finding the right section as well as for https://github.com/faustedition/faust-web/issues/330 it would be useful to integrate that info into document_metadata. Here is a commented YAML (for readability) version of the current & desired content:
```yaml
# for every manuscript:
- sigil: 2_H                            # sigil_t, used for reference and for building filenames
  document: faust/2/gsa_391098.xml      # path to metadata xml; suffix of faustUri
  base: transcript/gsa/391098/          # path to transcripts
  # type: print                         # for prints
  text: 391098.xml                      # filename of textual transcript
  sigils:                               # Manuscript tables
    headNote: Gebundenes Konvolut, 188 Blätter nebst Einband. – ‚Faust II‘.
    classification: Mundum
    idno_faustedition: 2 H
    idno_gsa_1: GSA 25/XIX,3
    idno_gsa_2: GSA 25/W 1804
    idno_gsa_ident: '391098'
    idno_wa_faust: 2 H
    idno_fischer_lamberg: 2 R
    idno_kraeuter: Eigen Poetisches 38.epsilon
    note_gsa_1: ''
    collection: ''
    repository: gsa
  page:                                # for every page: (currently empty for prints)
  - doc:
    - uri: 0001.xml                    # doctranscript filename
      imgLink: 8472954e-2177-4d16-8015-767fe34c49d1.svg  # imglink filename
      img:                             # list of image paths & filenames
      - gsa/391098/391098_0001
    empty: false                       # "empty" page?
    # TODO Following fields might be useful:
    section: 1                         # text transcript section, replaces pages.json
    scene: 2.1.1                       # scene for generating the
  - doc: …
```
