### ISSUE TITLE
Non-transcribed pages still jump back to TOC

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#523]
E.g., see [the title pages of _Der Tragödie erster Teil_](http://dev.faustedition.net/document?sigil=A&page=33&view=facsimile_text). The text views jump back to the TOC here, although they should display [section 4](http://dev.faustedition.net/document?sigil=A&page=33&view=facsimile_text&section=4). For page 33, we even have a `<pb>` in the textual transcript.

**Comment by thvitt** [comment]
Enriched XML encoding:
```xml
                    </div>   <!-- f:section=3 -->
                    <figure type="swelledRule"/>
                    <pb facs="A8_IIIB18_0024.tif" n="24" f:docTranscriptNo="32" f:hasDocTranscript="no"/>
                    <pb facs="A8_IIIB18_0025.tif" n="25" f:docTranscriptNo="33" f:hasDocTranscript="no"/>
                    <div xml:id="d179533e1720" n="1.1.1" f:first-verse="354" f:last-verse="4612">
                        <head n="before_354_a" rend="centered big letter-spaced">Der
                            Tragödie<lb/>Erſter Theil.</head>
                        <figure type="swelledRule"/>
                        <pb facs="A8_IIIB18_0026.tif" n="26" f:docTranscriptNo="34" f:hasDocTranscript="no"/>
                        <pb facs="A8_IIIB18_0027.tif" n="27" f:docTranscriptNo="35" f:hasDocTranscript="no"/>
                        <figure type="swelledRule"/>
                        <div f:section="4" f:verse-range="354 807" f:scene="1.1.1" n="1.1.1" xml:id="scene_1.1.1" f:label="Nacht." type="scene" f:first-verse="354" f:last-verse="807">
```

This is the YAMLified excerpt from document_metadata.js:
```yaml
  - doc: # 31 ✔
    - img:
      - print/A8_IIIB18/A8_IIIB18_0023
    section: 3
    div: 1.0.3
  - doc: # 32 ✘
    - img:
      - print/A8_IIIB18/A8_IIIB18_0024
  - doc: # 33 ✘, though there’s a pb
    - img:
      - print/A8_IIIB18/A8_IIIB18_0025
  - doc: # 34 ✘, no pb
    - img:
      - print/A8_IIIB18/A8_IIIB18_0026
    div: 1.1.1
  - doc: # 35 ✘, though there’s a pb
    - img:
      - print/A8_IIIB18/A8_IIIB18_0027
    div: 1.1.1
  - doc: # 36 ✓
    - img:
      - print/A8_IIIB18/A8_IIIB18_0028
    section: 4
    div: 1.1.1
```
actually, the div detection is wrong & should be 1.1, see #522
