### ISSUE TITLE
speaker on new line in app on 5357

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#588]
Note the `|` in the printed text:
![grafik](https://user-images.githubusercontent.com/10358005/44751921-b8eef400-ab19-11e8-9a2d-d9c037daa18a.png)
It would be logical, I think, to render `speaker` on a new line sinces this is how `speaker` generally appears. What do you think?

**Comment by thvitt** [comment]
When enforcing block rendering for speakers this looks rather torn apart:

![.speaker {display: block;}](https://user-images.githubusercontent.com/1906208/44773664-6d683480-ab71-11e8-8ae6-12283e9c7a6c.png)

**Comment by thvitt** [comment]
Alternative with a 'simple' line break when inside rdg and when not the first child:

![screenshot_138](https://user-images.githubusercontent.com/1906208/44774149-a2c15200-ab72-11e8-96f7-822512c5194b.png)

```css
.rdg .speaker::before { content: '\A'; white-space: pre; }
.rdg .speaker:first-child::before { content: ''; white-space:  normal }
```
